---

###
# MATTERMOST
###

# Version
mattermost_version: 5.5.1
mattermost_url: "https://releases.mattermost.com/{{ mattermost_version }}/mattermost-{{ mattermost_version }}-linux-amd64.tar.gz"

# User
mattermost_user: mattermost
mattermost_group: mattermost

# Database
mattermost_DBHost: "{{ hostvars[inventory_hostname].ip }}"
mattermost_DBPort: 5432
mattermost_DBName: mattermost
mattermost_DBUser: mattermost
mattermost_DBPassword: "bkzuhbeASbpzedDJ"
mattermost_DBDriver: postgres
mattermost_DBDatasource: "{{ mattermost_DBDriver }}://{{ mattermost_DBUser }}:{{ mattermost_DBPassword }}@{{ mattermost_DBHost }}:{{ mattermost_DBPort }}/{{ mattermost_DBName }}?sslmode=disable&connect_timeout=10"

# Configuration
mattermost_site_url: "http://mattermost.example.com:{{ mattermost_listen_port }}/"

# Port
mattermost_listen_port: 8065
