---

- name: MATTERMOST | Manage Postgresql
  import_tasks: postgresql.yml

- name: MATTERMOST | Manage user
  import_tasks: user.yml

- name: MATTERMOST | Download packages
  unarchive:
    src: "{{ mattermost_url }}"
    dest: /opt
    remote_src: yes
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_group }}"

- name: MATTERMOST | Create directories
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_group }}"
    mode: 0755
  with_items:
    - /opt/mattermost/data

- name: MATTERMOST | Configuration
  template:
    src: "opt/mattermost/config/config.json.j2"
    dest: "/opt/mattermost/config/config.json"
    owner: "{{ mattermost_user }}"
    group: "{{ mattermost_group }}"
    mode: 0644

- name: MATTERMOST | Configure systemd service
  template:
    src: "lib/systemd/system/mattermost.service.j2"
    dest: "/lib/systemd/system/mattermost.service"
    owner: root
    group: root
    mode: 0644
  notify: Restart mattermost

- name: MATTERMOST | Manage logs
  file:
    src: /opt/mattermost/logs
    dest: /var/log/mattermost
    state: link
    owner: root
    group: root
