---

- name: MATTERMOST POSTGRESQL | Create database
  postgresql_db:
    name: "{{ mattermost_DBName }}"
    port: "{{ mattermost_DBPort }}"
    state: present
  become: yes
  become_user: postgres

- name: MATTERMOST POSTGRESQL | Create role
  postgresql_user:
    db: "{{ mattermost_DBName }}"
    name: "{{ mattermost_DBUser }}"
    password: "md5{{ (mattermost_DBPassword + mattermost_DBUser)|hash('md5') }}"
    port: "{{ mattermost_DBPort }}"
    priv: ALL
    state: present
    encrypted: yes
  become: yes
  become_user: postgres

- name: MATTERMOST POSTGRESQL | Configure rules
  lineinfile:
    path: "/etc/postgresql/9.6/main/pg_hba.conf"
    line: "host    all           all             {{ hostvars[item].ip }}/32           md5"
    state: present
  with_items: "{{ groups['mattermost'] }}"
  notify: Restart postgresql
